#!/bin/sh -ue

# This script runs the tests of the project.
#
# See [README.md] for an explanation of this and how CI should use it.

# We need Karaf feature to be installed into local M2 repo. Otherwise, it won't be found by
# integration tests. Hence, we use "install" not "verify" here.
./mvnw -T1C -nsu install
